// @ts-check

import apiSidebar from './docs/api-reference/sidebar.ts';

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docsSidebar: [
    {type: 'autogenerated', dirName: 'introduction'},
    {type: 'autogenerated', dirName: 'getting-started'},
    {type: 'autogenerated', dirName: 'authentication'},
    {type: 'autogenerated', dirName: 'concepts'},
    {type: 'autogenerated', dirName: 'guides'},
    {
      type: 'category',
      label: 'API Reference',
      link: {type: 'generated-index', title: 'API Reference'},
      items: apiSidebar,
    },
  ],
};

export default sidebars;
