// @ts-check

import apiSidebar from './docs/api-reference/sidebar.ts';

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docsSidebar: [
    {type: 'autogenerated', dirName: 'introduction'},
    {type: 'autogenerated', dirName: 'quick-start'},
    {type: 'autogenerated', dirName: 'authentication'},
    {type: 'autogenerated', dirName: 'concepts'},
    ...apiSidebar.filter((/** @type {any} */ item) => !(item.type === 'doc' && item.id === 'api-reference/proabono-api-live')),
    {type: 'autogenerated', dirName: 'guides'},
  ],
};

export default sidebars;
